name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile main.py
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: smitheryGUI-windows
        path: dist/main.exe

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y python3-pyqt6
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile main.py
        
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: smitheryGUI-linux
        path: dist/main

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          smitheryGUI-windows/main.exe
          smitheryGUI-linux/main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}