name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
  push:
    tags:
      - 'v*'

jobs:
  create-tag:
    runs-on: ubuntu-22.04
    if: github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Create tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    needs: [create-tag]
    if: always() && (needs.create-tag.result == 'success' || needs.create-tag.result == 'skipped')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile main.py
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: smitheryGUI-windows
          path: dist/main.exe

  build-linux:
    needs: [create-tag]
    if: always() && (needs.create-tag.result == 'success' || needs.create-tag.result == 'skipped')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:neon/qt6
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-declarative-dev libqt6sql6 libqt6core6 libqt6gui6 libqt6widgets6
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile main.py
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: smitheryGUI-linux
          path: dist/main

  create-release:
    needs: [create-tag, build-windows, build-linux]
    if: always() && (needs.create-tag.result == 'success' || needs.create-tag.result == 'skipped')
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          name: Release ${{ github.event.inputs.version || github.ref_name }}
          files: |
            smitheryGUI-windows/main.exe
            smitheryGUI-linux/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}